yatube/about/urls.py
# файл about/urls.py
from django.urls import path

from .views import AboutAuthorView, AboutTechView

app_name = 'about'

urlpatterns = [
    path('author/', AboutAuthorView.as_view(), name='author'),
    path('tech/', AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_list, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),

]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path(
        'admin/',
        admin.site.urls),
    path(
        '',
        include(
            'posts.urls',
            namespace='posts')),
    path(
        'auth/',
        include(
            'users.urls',
            namespace='users')),
    path(
        'auth/',
        include('django.contrib.auth.urls')),
    path(
        'about/',
        include(
            'about.urls',
            namespace='about')),

]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts')
    group = models.ForeignKey(
        'Group',
        related_name='posts',
        on_delete=models.SET_NULL,
        blank=True,
        null=True)
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True)

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        related_name='comments',
        on_delete=models.CASCADE,)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments')
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following')

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'text', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User

posts_in_page = 10


def index(request):
    template = 'posts/index.html'
    posts = Post.objects.all()
    paginator = Paginator(posts, posts_in_page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, template, context)


def group_list(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, posts_in_page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/group_list.html'
    context = {'group': group, 'page_obj': page_obj
               }
    return render(request, template, context)


def profile(request, username):
    author = User.objects.get(username=username)
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user, author=author).exists()
    else:
        following = None
    posts_from_author = author.posts.all()
    paginator = Paginator(posts_from_author, posts_in_page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'posts': posts_from_author, 'author': author,
               'count': author.posts.all().count(), 'page_obj': page_obj,
               'following': following}
    return render(request, 'posts/profile.html', context)


@login_required
def add_comment(request, post_id):
    post = Post.objects.get(pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


def post_detail(request, post_id):
    form = CommentForm()
    post = Post.objects.get(pk=post_id)
    author = User.objects.get(pk=post.author_id)
    comments = post.comments.all()
    context = {
        'post': post,
        'count': author.posts.all().count(),
        'form': form,
        'comments': comments}
    return render(request, 'posts/post_detail.html', context)


@login_required()
def post_create(request):
    if request.method == 'POST':
        form = PostForm(
            request.POST or None,
            initial={
                'author': request.user},
            files=request.FILES or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            form.save()
            return redirect('posts:profile', post.author.username)
    else:
        form = PostForm(initial={'author': request.user})
    context = {'form': form, }
    return render(request, 'posts/create.html', context)


@login_required()
def post_edit(request, post_id):
    post = Post.objects.get(pk=post_id)
    is_edit = True
    if post.author != request.user:
        return redirect('users:login')
    else:
        if request.method == 'POST':
            form = PostForm(
                request.POST or None,
                files=request.FILES or None,
                instance=post
            )
            if form.is_valid():
                form.save()
                return redirect('posts:post_detail', post.pk)
        else:
            form = PostForm(instance=post)
        context = {'form': form, 'is_edit': is_edit}
        return render(request, 'posts/create.html', context)


@login_required
def follow_index(request):
    posts = (
        Post.objects.filter(
            author__following__user=request.user
        )
    )
    paginator = Paginator(posts, posts_in_page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    user = get_object_or_404(User,
                             username=username)
    if request.user == user or Follow.objects.filter(
            author=user).exists():
        return redirect('posts:index')
    else:
        Follow.objects.create(
            user=request.user,
            author=user)
    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    Follow.objects.filter(
        user=request.user,
        author=get_object_or_404(User,
                                 username=username)).delete()
    return redirect('posts:index')

yatube/templates/posts/create.html
{% extends 'base.html' %}
{% load user_filters %}
{% block title %}
{% if request.resolver_match.view_name  == 'posts:post_create' %}
<title>
  Доабвление поста
</title>
{% else %}
<title>
  Редактирование поста
</title>
{% endif %}
{% endblock %}
{% include 'includes/header.html' %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Новый пост
          </div>
          <form method="post"  enctype="multipart/form-data">
            <div class="card-body">
              <div class="form-group row my-3 p-3">
                <label for="id_text">
                Текст поста
                <span class="required text-danger" >*</span>
                </label>
                {{form.text|addclass:'form-control' }}
                <small id="id_text-help" class="form-text text-muted">
                Текст нового поста
                </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_group">
                Группа
                </label>
                {{form.group|addclass:'form-control' }}
                <small id="id_group-help" class="form-text text-muted">
                Группа, к которой будет относиться пост
                </small>
              </div>
              <div class="form-group row my-3 p-3">
                    <label for="id_image">
                      Картинка
                    </label>
                {{form.image|addclass:'form-control' }}
                  </div>
                  <div class="d-flex justify-content-end">
              {{form.author}}
              {% if request.resolver_match.view_name  == 'posts:post_create' %}
              {{is_edit}}
              <input type="submit" value="Добавить">
              {% else %}
              <input type="submit" value="Сохранить">
              {% endif %}
            </div>
            {% csrf_token %}
          </form>
        </div>
      </div>
    </div>
  </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
<title>
  Посты авторов, на которого Вы подписаны
</title>
{% endblock %}
{% include 'includes/header.html' %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
<div class="container py-5">
  <h1>
    Посты авторов, на которых Вы подписаны
  </h1>

  {% for post in page_obj %}
  <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
    <p>
      <a href="{% url 'posts:post_detail' post.pk  %}">{{post}} </a>
    </p>
    {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  </article>
  <hr>
  {% endfor %}

  {% include 'includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
<title>
  {{group.title}}
</title>
{% endblock %}
{% block content %}
{% load thumbnail %}
<div class="container py-5">
<h1>{{ group.title }}</h1>
<p>{{ group.description }}</p>
  {% for post in page_obj %}
  <article>
    <ul>
      <li>
        Автор: {{post.author.get_full_name}}
      </li>
      <li>
        Дата публикации: {{post.pub_date}}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
    <p>
      <a href="{% url 'posts:post_detail' post.pk  %}">{{post}} </a>
    </p>
  </article>
  <hr>
  {% endfor %}
  {% include 'includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
<title>
  Последние обновления на сайте
</title>
{% endblock %}
{% include 'includes/header.html' %}
{% load cache %}
{% block content %}
{% cache 20 index_page page_obj %}
{% include 'posts/includes/switcher.html' %}
<div class="container py-5">
  <h1>
    Последние обновления на сайте
  </h1>

  {% for post in page_obj %}
  <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
    <p>
      <a href="{% url 'posts:post_detail' post.pk  %}">{{post}} </a>
    </p>
    {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}

  </article>
  <hr>
  {% endfor %}

  {% include 'includes/paginator.html' %}
</div>
{% endcache %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load user_filters %}
{% block title %}
{% load thumbnail %}
<title>Пост {{ post.text|truncatechars:30 }}</title>
{% endblock %}
{% include 'includes/header.html' %}
{% block content %}
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации: {{post.pub_date}}
      </li>
      <li class="list-group-item">
        {% if post.group %}
        Группа: {{post.group}}
        <a href="{% url 'posts:group_list' post.group.slug %}">
        все записи группы
        {% endif %}
        </a>
      </li>
      <li class="list-group-item">
        Автор: {{post.author.get_full_name}}
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего постов автора:  <span >{{count}}</span>
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:profile' post.author.username  %}">
        все посты пользователя
        </a>
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">

    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
    <p>
      {{post}}
    </p>
    {% if request.user == post.author%}
    <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk  %}">
              редактировать запись
            </a>
    {% endif %}

    {% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>

    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}
        <div class="form-group mb-2">

          {{ form.text|addclass:"form-control" }}

        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}
    {% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %}

  </article>
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %}
<title>
  Профайл пользователя {{ author.get_full_name }}
</title>
{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="mb-5">
  <h1>Все посты пользователя {{ author.get_full_name }}</h1>
  <h3>Всего постов: {{count}} </h3>
     {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}

      {% if request.user != author %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
    {% endif %}
   {% endif %}
  <article>
    {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ author.get_full_name }}
        <a href="{% url 'posts:profile' post.author.username  %}">все посты пользователя</a>
      </li>
      <li>
        Дата публикации: {{post.pub_date}}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
    <p>
      <a href="{% url 'posts:post_detail' post.pk  %}">{{post}} </a>
    </p>
    {% endfor %}
    <a href="">подробная информация </a>
  </article>
  <a href="">все записи группы</a>
  <hr>
  {% include 'includes/paginator.html' %}
</div>
</div>
{% endblock %}